apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- image-nodejs-cache-resource.yaml
- image-nodejs-internal-registry-resource.yaml
- image-nodejs-quay-resource.yaml
- pipeline.yaml



