apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- image-httpd-cache-resource.yaml
- image-httpd-internal-registry-resource.yaml
- image-httpd-quay-resource.yaml
- pipeline.yaml



