apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- image-tomcat-cache-resource.yaml
- image-tomcat-internal-registry-resource.yaml
- image-tomcat-quay-resource.yaml
- pipeline.yaml



